import Head from 'next/head';
import { useRunInBrowser } from '@/lib/helpers/useRunInBrowser';

export default function Home() {
	const inBrowser = useRunInBrowser();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				{inBrowser && <div />}
			</main>
		</>
	);
}
